name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Install Trunk
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.21.3/trunk-x86_64-unknown-linux-gnu.tar.gz | sudo tar -xzf- -C /usr/local/bin

      - name: Install wasm-bindgen-cli
        run: wget -qO- https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.121/wasm-bindgen-0.2.121-x86_64-unknown-linux-gnu.tar.gz | sudo tar -xzf- --strip-components=1 -C /usr/local/bin

      - name: Build Frontend
        working-directory: frontend
        run: trunk build --release

      - name: Cargo Check
        run: cargo check --workspace

      - name: Cargo Test
        run: cargo test --workspace
